# 作業目標:
    了解 Convolution 卷積的組成

# 作業重點:
    修改 a_slice_prev, 檢查 Z 的輸出

In [1]:
import numpy as np

In [2]:
# GRADED FUNCTION: conv_single_step
def conv_single_step(a_slice_prev, W, b):
    """
    定義一層 Kernel (內核), 使用的參數說明如下
    Arguments:
        a_slice_prev -- 輸入資料的維度
        W -- 權重, 被使用在 a_slice_prev
        b -- 偏差參數 
    Returns:
        Z -- 滑動窗口（W，b）卷積在前一個 feature map 上的結果
    """

    # 定義一個元素介於 a_slice and W
    s = a_slice_prev * W
    # 加總所有的 "s" 並指定給Z.
    Z = np.sum(s)
    # Add bias b to Z. 這是 float() 函數,
    Z = float(Z + b)

    return Z

In [3]:
'''

np.random.seed(1)
#定義一個 axaxd 的 feature map
a_slice_prev = 
W = 
b = np.random.randn(1, 1, 1)

#取得計算後,卷積矩陣的值
Z = conv_single_step(a_slice_prev, W, b)
print("Z =", Z)
'''
np.random.seed(1)

# 定義一個 axaxd 的 feature map
a_slice_prev = np.random.randn(2, 2, 2)
W = np.random.randn(2, 2, 2)
b = np.random.randn(1, 1, 1)

# 取得計算後,卷積矩陣的值
Z = conv_single_step(a_slice_prev, W, b)
print("Z =", Z)

Z = 5.356930357545693


In [4]:
a_slice_prev

array([[[ 1.62434536, -0.61175641],
        [-0.52817175, -1.07296862]],

       [[ 0.86540763, -2.3015387 ],
        [ 1.74481176, -0.7612069 ]]])

In [5]:
W

array([[[ 0.3190391 , -0.24937038],
        [ 1.46210794, -2.06014071]],

       [[-0.3224172 , -0.38405435],
        [ 1.13376944, -1.09989127]]])

In [7]:
b

array([[[-0.17242821]]])

In [6]:
a_slice_prev * W

array([[[ 0.51822968,  0.15255393],
        [-0.77224411,  2.21046634]],

       [[-0.27902231,  0.88391596],
        [ 1.97821426,  0.83724482]]])